version: '3'

services:
  # Backend / Database
  database:
    image: database
    build: ../backend/database
    restart: always
    volumes:
      - ../backend/database/scripts:/docker-entrypoint-initdb.d
    networks:
      - back
    environment: 
      - MYSQL_ROOT_PASSWORD=toor
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ../backend/kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  # Backend / Kambi Scraper
  kambi:
    image: kambi
    build: ../backend/scraper/kambi
    restart: always
    depends_on:
      - database
    networks:
      - front
      - back
    ports:
      - 3000:3000

  sbtech:
    image: sbtech
    build: ../backend/scraper/sbtech
    restart: always
    depends_on:
      - database
    networks:
      - front
      - back
    ports:
      - 3001:3001

networks:
  front:
    driver: bridge
  back:
    driver: bridge
  docker-network:
    driver: bridge