version: '3'

services:
  # Backend / Database
  database:
    image: database
    build: ../backend/database
    restart: always
    volumes:
      - ../backend/database/scripts:/docker-entrypoint-initdb.d
    networks:
      - back
    environment: 
      - MYSQL_ROOT_PASSWORD=toor
  
  # Backend / Kambi Scraper
  kambi:
    image: kambi
    build: ../backend/scraper/kambi
    restart: always
    depends_on:
      - database
    networks:
      - front
      - back
    ports:
      - 3000:3000

  sbtech:
    image: sbtech
    build: ../backend/scraper/sbtech
    restart: always
    depends_on:
      - database
    networks:
      - front
      - back
    ports:
      - 3001:3001

networks:
  front:
    driver: bridge
  back:
    driver: bridge
  docker-network:
    driver: bridge